//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class AutomartEntities1 : DbContext
{
    public AutomartEntities1()
        : base("name=AutomartEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Location> Locations { get; set; }
    public DbSet<RegisteredCustomer> RegisteredCustomers { get; set; }
    public DbSet<vehicle> vehicles { get; set; }
    public DbSet<Person> People { get; set; }
}
